LOGGER_FORMAT: "text"
LOGGER_LEVEL: "debug"

POSTGRES_DATABASE: "actor"
POSTGRES_ADDRESS: "localhost:5432"
POSTGRES_USERNAME: "postgres"
POSTGRES_PASSWORD: "root"
POSTGRES_MAX_IDLE_CONN: "10"
POSTGRES_MAX_OPEN_CONN: "10"
POSTGRES_LOG_ENABLED: "true"

MONGO_ADDRESS: "mongodb://localhost:27017"
MONGO_DATABASE: "registrant"
MONGO_USERNAME: "root"
MONGO_PASSWORD: "root"
MONGO_MAX_POOL: "10"

NEO4J_ADDRESS: "bolt://localhost:7687"
NEO4J_USERNAME: "neo4j"
NEO4J_PASSWORD: "root"
NEO4J_MAX_CONN_POOL: "10"
NEO4J_VERIFY_HOSTNAME: "false"
NEO4J_MAX_CONN_LIFETIME: "1"
NEO4J_LOG_ENABLED: "true"
NEO4J_LOG_LEVEL: "3"

ELASTICSEARCH_ADDRESS: "http://localhost:9200"
ELASTICSEARCH_USERNAME: "root"
ELASTICSEARCH_PASSWORD: "root"
ELASTICSEARCH_MAX_CONN_PER_HOST: "10"
ELASTICSEARCH_MAX_IDLE_PER_HOST: "10"

REDIS_ADDRESS: "localhost:6379"
REDIS_PASSWORD: "root"
REDIS_DATABASE: "root"
REDIS_POOL_SIZE: "10"
REDIS_MIN_IDLE_CONN: "10"