version: '3'

networks:
  frame:
    driver: bridge

services:
  app:
    build:
      dockerfile: docker/Dockerfile.test
      context: ..
    environment:
      LOGGER_FORMAT: 'text'
      LOGGER_LEVEL: 'debug'
      POSTGRES_DATABASE: 'goframe'
      POSTGRES_ADDRESS: 'localhost:5432'
      POSTGRES_PARAMS: 'sslmode=disable'
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_MAX_IDLE_CONN: '10'
      POSTGRES_MAX_OPEN_CONN: '10'
      POSTGRES_LOG_LEVEL: '2'
      MONGO_ADDRESS: 'mongodb://localhost:27017'
      MONGO_DATABASE: 'goframe'
      MONGO_USERNAME: 'root'
      MONGO_PASSWORD: 'root'
      MONGO_MAX_POOL: '10'
      NEO4J_ADDRESS: 'bolt://localhost:7687'
      NEO4J_USERNAME: 'root'
      NEO4J_PASSWORD: 'root'
      NEO4J_VERIFY_HOSTNAME: 'false'
      NEO4J_LOG_ENABLED: 'true'
      NEO4J_LOG_LEVEL: '3'
      NEO4J_MAX_CONN_POOL: '10'
      NEO4J_MAX_CONN_LIFETIME: '1'
      ELASTICSEARCH_ADDRESS: 'http://localhost:9200'
      ELASTICSEARCH_USERNAME: 'root'
      ELASTICSEARCH_PASSWORD: 'root'
      ELASTICSEARCH_MAX_CONN_PER_HOST: '10'
      ELASTICSEARCH_MAX_IDLE_PER_HOST: '10'
      REDIS_ADDRESS: 'localhost:6379'
      REDIS_PASSWORD: 'root'
      REDIS_DATABASE: '1'
      REDIS_POOL_SIZE: '10'
      REDIS_MIN_IDLE_CONN: '10'
    networks:
      - frame

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: 'goframe'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    expose:
      - 5432
    networks:
      - frame

  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
    expose:
      - 27017
    networks:
      - frame

  neo4j:
    image: neo4j:4.1-enterprise
    environment:
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_AUTH: 'root:root'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
    expose:
      - 7687
    networks:
      - frame

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      ELASTIC_USERNAME: 'root'
      ELASTIC_PASSWORD: 'root'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      discovery.type: 'single-node'
    expose:
      - 9200
    networks:
      - frame

  redis:
    image: redis:6-alpine
    environment:
      REDIS_PASSWORD: 'root'
    expose:
      - 6379
    networks:
      - frame